### ISSUE TITLE
Generate URLS from transcript file

### ISSUE THREAD

**Issue by easherma** [chihacknight/chihacknight-yt-interface#4]
- [ ] Read transcript file
- [ ] For a time range/group of words, parse into youtube url to share ex (https://youtu.be/rD7ByPxRdNU?t=22s)

**Comment by RBecker262** [comment]
I have this working using BeautifulSoup, very short and easy process, can show Tuesday night. I have a couple of questions. First is where will the youtube link for each video come from, there isn't one in the sample file so right now I start with this link string and build the time portion for each group of text I find in the XML file...

link = 'https://youtu.be/linktovideo?t='

Also, there is an end time to each text block but I am only building the start time in the link at the moment as you had indicated. Figure the user can decide when to stop the video. What do you think?

**Comment by easherma** [comment]
This is implemented in Pandas at the moment. 

See https://github.com/chihacknight/chihacknight-yt-interface/blob/master/ETL_data.ipynb
